#!/usr/bin/env python3
"""
Clash Verge Rev 一键配置与环境一致性核验工具 (Shadowrocket 环境对齐专用)

目标：
  将当前 Mac（或任意用户电脑）上的 Clash Verge Rev 配置与 Shadowrocket 规则环境 100% 对齐，
  确保在“系统代理 + 规则（Rule）模式、关闭 TUN、关闭全局”的前提下，分流效果与 Shadowrocket 完全一致。

功能：
  1. 自动定位本机 Clash Verge Rev 数据目录与激活 Profile。
  2. 一键注入与 Shadowrocket 完全一致的云端规则集（小红书、抖音、快手、Claude、公司网络等）。
  3. 探测云端规则集（GitHub Raw）可用性与规则条数。
  4. 运行态安全检查：核验是否为规则模式（非全局）、TUN 是否处于关闭状态。
  5. 实时链路拨测：测试 Clash 端口对小红书、抖音、快手及 Claude 的实际分流响应。
  6. 输出与 Shadowrocket 基准环境的一致性对比报告。

使用方式：
  python3 scripts/setup_clash_verge.py          # 一键配置并验证
  python3 scripts/setup_clash_verge.py --check  # 仅核验当前状态，不修改任何文件

任意 Mac 终端单行执行：
  curl -fsSL https://raw.githubusercontent.com/SimileciWH/shadowrocket-config/main/scripts/setup_clash_verge.py | python3
"""

import os
import sys
import re
import time
import subprocess
import urllib.request
import urllib.error
from pathlib import Path

# ANSI 颜色定义
GREEN = "\033[92m"
YELLOW = "\033[93m"
RED = "\033[91m"
BLUE = "\033[94m"
CYAN = "\033[96m"
BOLD = "\033[1m"
RESET = "\033[0m"

REPO_RAW_BASE = "https://raw.githubusercontent.com/SimileciWH/shadowrocket-config/main/clash"
DIRECT_URL = f"{REPO_RAW_BASE}/rules_direct.yaml"
PROXY_URL = f"{REPO_RAW_BASE}/rules_proxy.yaml"
COMPANY_URL = f"{REPO_RAW_BASE}/rules_company.yaml"

# 国内高速直连备用镜像源
FALLBACK_BASES = [
    "https://fastly.jsdelivr.net/gh/SimileciWH/shadowrocket-config@main/clash",
    "https://ghproxy.net/https://raw.githubusercontent.com/SimileciWH/shadowrocket-config/main/clash",
]

# 注入到 Clash Verge Rev 的 Merge 扩展模板
MERGE_CONTENT = """# Profile Enhancement Merge for Clash Verge Rev
# Generated by shadowrocket-config sync script
# Auto-syncs rules from GitHub: SimileciWH/shadowrocket-config

rule-providers:
  sr-direct:
    type: http
    behavior: classical
    format: yaml
    interval: 86400
    url: "https://raw.githubusercontent.com/SimileciWH/shadowrocket-config/main/clash/rules_direct.yaml"
    path: ./ruleset/sr-direct.yaml

  sr-proxy:
    type: http
    behavior: classical
    format: yaml
    interval: 86400
    url: "https://raw.githubusercontent.com/SimileciWH/shadowrocket-config/main/clash/rules_proxy.yaml"
    path: ./ruleset/sr-proxy.yaml

  sr-company:
    type: http
    behavior: classical
    format: yaml
    interval: 86400
    url: "https://raw.githubusercontent.com/SimileciWH/shadowrocket-config/main/clash/rules_company.yaml"
    path: ./ruleset/sr-company.yaml

prepend-proxy-groups:
  - name: CORP-WINDOWS
    type: select
    proxies:
      - DIRECT
      - 节点选择

  - name: justg-vps-RU-direct
    type: select
    proxies:
      - 节点选择
      - DIRECT

prepend-rules:
  - RULE-SET,sr-company,CORP-WINDOWS
  - RULE-SET,sr-proxy,节点选择
  - RULE-SET,sr-direct,DIRECT
"""

def find_verge_dir():
    candidates = [
        Path.home() / "Library" / "Application Support" / "io.github.clash-verge-rev.clash-verge-rev",
        Path.home() / "Library" / "Application Support" / "clash-verge-rev",
        Path.home() / "Library" / "Application Support" / "clash-verge",
        Path.home() / ".config" / "clash-verge-rev",
    ]
    for c in candidates:
        if c.exists() and (c / "profiles.yaml").exists():
            return c
    return None

def fetch_single_url(url, timeout=5):
    req = urllib.request.Request(
        url,
        headers={"User-Agent": "Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7)"}
    )
    with urllib.request.urlopen(req, timeout=timeout) as resp:
        if resp.status == 200:
            data = resp.read().decode("utf-8")
            count = len(re.findall(r"^\s*-\s+", data, re.MULTILINE))
            return True, count, data
        return False, 0, f"HTTP {resp.status}"

def test_url_fetch(primary_url, filename, timeout=5):
    """Test primary URL, and auto fallback to CDN mirrors if blocked by GFW."""
    try:
        ok, count, data = fetch_single_url(primary_url, timeout=timeout)
        if ok:
            return True, count, "GitHub Raw (直连)"
    except Exception:
        pass

    # 尝试国内高速镜像
    for base in FALLBACK_BASES:
        fallback_url = f"{base}/{filename}"
        try:
            ok, count, data = fetch_single_url(fallback_url, timeout=timeout)
            if ok:
                return True, count, f"CDN镜像加速 ({base.split('/')[2]})"
        except Exception:
            continue

    return False, 0, "所有节点连接均超时或被阻断"

def test_proxy_connect(port, target_url, timeout=4):
    """Test connecting to a URL through Clash mixed port using curl."""
    try:
        cmd = [
            "curl", "-I", "-sS", "-m", str(timeout),
            "-x", f"http://127.0.0.1:{port}",
            target_url
        ]
        res = subprocess.run(cmd, capture_output=True, text=True)
        if res.returncode == 0 and ("HTTP/" in res.stdout or "200" in res.stdout or "301" in res.stdout or "302" in res.stdout):
            first_line = res.stdout.splitlines()[0] if res.stdout else "OK"
            return True, first_line.strip()
        return False, res.stderr.strip() or "Connection failed"
    except Exception as e:
        return False, str(e)

def parse_simple_yaml_map(filepath):
    result = {}
    if not filepath.exists():
        return result
    with open(filepath, "r", encoding="utf-8") as f:
        for line in f:
            line = line.strip()
            if not line or line.startswith("#"):
                continue
            if ":" in line:
                k, v = line.split(":", 1)
                result[k.strip()] = v.strip().strip("'\"")
    return result

def main():
    check_only = "--check" in sys.argv or "--check-only" in sys.argv

    print(f"\n{BOLD}{CYAN}==================================================================={RESET}")
    print(f"{BOLD}{CYAN}      Clash Verge Rev 与 Shadowrocket 环境对齐与一致性校验工具      {RESET}")
    print(f"{BOLD}{CYAN}==================================================================={RESET}\n")

    # 1. 寻找 Clash Verge Rev 数据目录
    verge_dir = find_verge_dir()
    if not verge_dir:
        print(f"[{RED}FAIL{RESET}] 未找到 Clash Verge Rev 数据目录。")
        print(f"       请确认本机已安装并启动过 Clash Verge Rev。")
        sys.exit(1)

    print(f"[{GREEN}OK{RESET}] 定位到 Clash Verge Rev 数据目录: {verge_dir}")

    # 2. 读取 profiles.yaml 识别当前激活配置
    profiles_yaml_path = verge_dir / "profiles.yaml"
    with open(profiles_yaml_path, "r", encoding="utf-8") as f:
        profiles_content = f.read()

    current_match = re.search(r"^current:\s*([a-zA-Z0-9_-]+)", profiles_content, re.MULTILINE)
    current_uid = current_match.group(1).strip() if current_match else None

    if not current_uid:
        print(f"[{RED}FAIL{RESET}] 未在 profiles.yaml 中找到激活配置 (current)。")
        sys.exit(1)

    profile_pattern = rf"-\s+uid:\s+{re.escape(current_uid)}\b(.*?)(?=\n-\s+uid:|\Z)"
    profile_match = re.search(profile_pattern, profiles_content, re.DOTALL)

    profile_name = current_uid
    merge_uid = None

    if profile_match:
        block = profile_match.group(1)
        name_m = re.search(r"name:\s*(.+)", block)
        if name_m:
            profile_name = name_m.group(1).strip().strip("'\"")
        merge_m = re.search(r"merge:\s*([a-zA-Z0-9_-]+)", block)
        if merge_m:
            merge_uid = merge_m.group(1).strip()

    print(f"[{GREEN}OK{RESET}] 当前生效 Profile: {BOLD}{profile_name}{RESET} (UID: {current_uid})")

    # 3. 确定 Merge 文件位置
    profiles_dir = verge_dir / "profiles"
    if not profiles_dir.exists():
        profiles_dir.mkdir(parents=True, exist_ok=True)

    if not merge_uid or merge_uid == "null":
        merge_uid = f"merge_{int(time.time())}"
        print(f"[{YELLOW}WARN{RESET}] 当前 Profile 未关联 Merge 扩展，将自动绑定: {merge_uid}")
        if "option:" in block:
            new_block = re.sub(r"(option:\s*\n)", rf"\1    merge: {merge_uid}\n", block, count=1)
            profiles_content = profiles_content.replace(block, new_block)
        else:
            new_block = block + f"\n  option:\n    merge: {merge_uid}\n"
            profiles_content = profiles_content.replace(block, new_block)

        merge_item_yaml = f"- uid: {merge_uid}\n  type: merge\n  name: SR-Rules-AutoSync\n  file: {merge_uid}.yaml\n  updated: {int(time.time())}\n"
        profiles_content = re.sub(r"(items:\s*\n)", rf"\1{merge_item_yaml}", profiles_content, count=1)

        if not check_only:
            with open(profiles_yaml_path, "w", encoding="utf-8") as f:
                f.write(profiles_content)

    merge_file = profiles_dir / f"{merge_uid}.yaml"

    # 4. 执行写入（非只读模式）
    if not check_only:
        with open(merge_file, "w", encoding="utf-8") as f:
            f.write(MERGE_CONTENT)
        print(f"[{GREEN}OK{RESET}] 已一键写入 Shadowrocket 对齐规则到 Merge 扩展文件 ({merge_file.name})")
    else:
        print(f"[{BLUE}INFO{RESET}] 处于仅核验模式 (--check)，未修改文件。")

    # 5. 校验远程 GitHub 规则源（支持国内 CDN / 镜像自动回退）
    print(f"\n{BOLD}正在检测云端规则源可用性...{RESET}")
    direct_ok, direct_count, direct_src = test_url_fetch(DIRECT_URL, "rules_direct.yaml")
    proxy_ok, proxy_count, proxy_src = test_url_fetch(PROXY_URL, "rules_proxy.yaml")
    company_ok, company_count, company_src = test_url_fetch(COMPANY_URL, "rules_company.yaml")

    print(f"  - 直连规则源 (rules_direct.yaml):  {'[ ' + GREEN + '可用' + RESET + ' ]' if direct_ok else '[ ' + RED + '异常' + RESET + ' ]'} (包含小红书、抖音、快手等 {direct_count} 条) 来源: {direct_src}")
    print(f"  - 代理规则源 (rules_proxy.yaml):   {'[ ' + GREEN + '可用' + RESET + ' ]' if proxy_ok else '[ ' + RED + '异常' + RESET + ' ]'} (包含 Claude / Anthropic 等 {proxy_count} 条) 来源: {proxy_src}")
    print(f"  - 公司规则源 (rules_company.yaml): {'[ ' + GREEN + '可用' + RESET + ' ]' if company_ok else '[ ' + RED + '异常' + RESET + ' ]'} (包含内部 Jenkins / 内网 {company_count} 条) 来源: {company_src}")

    # 6. 读取运行模式与端口设置
    verge_config = parse_simple_yaml_map(verge_dir / "verge.yaml")
    clash_config_path = verge_dir / "clash-verge.yaml"
    clash_config = parse_simple_yaml_map(clash_config_path)

    mixed_port = int(verge_config.get("verge_mixed_port", clash_config.get("mixed-port", 7897)))
    tun_mode = verge_config.get("enable_tun_mode", "false").lower() == "true"
    current_mode = clash_config.get("mode", "rule").lower()

    # 如果检测到被误设为 global，自动修正为 rule
    if not check_only and current_mode == "global":
        print(f"[{YELLOW}FIX{RESET}] 检测到运行模式为 global，正在自动切换为 {BOLD}rule（规则模式）{RESET}...")
        with open(clash_config_path, "r", encoding="utf-8") as f:
            cf_text = f.read()
        cf_text = re.sub(r"^mode:\s*global", "mode: rule", cf_text, flags=re.MULTILINE)
        with open(clash_config_path, "w", encoding="utf-8") as f:
            f.write(cf_text)
        current_mode = "rule"
        print(f"[{GREEN}OK{RESET}] 已成功切换为 rule 规则分流模式！")

    # 7. 检测系统代理残留状态 (例如旧的 1082)
    import socket
    try:
        sc_out = subprocess.run(["scutil", "--proxy"], capture_output=True, text=True).stdout
        if "HTTPEnable : 1" in sc_out:
            port_m = re.search(r"HTTPPort\s*:\s*(\d+)", sc_out)
            sys_port = int(port_m.group(1)) if port_m else None
            if sys_port and sys_port != mixed_port:
                # 检查该残留端口是否死掉
                with socket.socket(socket.AF_INET, socket.SOCK_STREAM) as s:
                    s.settimeout(0.3)
                    dead = (s.connect_ex(("127.0.0.1", sys_port)) != 0)
                if dead:
                    print(f"[{YELLOW}WARN{RESET}] 检测到 macOS 系统代理当前指向已关闭的旧端口 {sys_port}（如 Shadowrocket 退出残留）！")
                    print(f"       会导致终端 curl 报 'Failed to connect after 2 ms'。")
                    print(f"       {BOLD}解决办法：请在 Clash Verge Rev 界面开启【系统代理 (System Proxy)】以覆盖为 {mixed_port}。{RESET}")
    except Exception:
        pass

    # 8. 探测 Clash 代理端口是否正在监听
    port_listening = False
    with socket.socket(socket.AF_INET, socket.SOCK_STREAM) as s:
        s.settimeout(0.5)
        port_listening = (s.connect_ex(("127.0.0.1", mixed_port)) == 0)

    # 8. 实时分流连通性测试（若 Clash 端口正在监听）
    probe_results = {}
    if port_listening:
        print(f"\n{BOLD}检测到 Clash 正在运行 (端口: {mixed_port})，开始实时分流拨测...{RESET}")
        targets = [
            ("小红书 (DIRECT)", "https://www.xiaohongshu.com/"),
            ("抖音 (DIRECT)", "https://www.douyin.com/"),
            ("快手 (DIRECT)", "https://www.kuaishou.com/"),
            ("Claude (PROXY)", "https://api.anthropic.com/"),
        ]
        for label, url in targets:
            ok, msg = test_proxy_connect(mixed_port, url)
            probe_results[label] = ok
            status_tag = f"{GREEN}成功 (200/OK){RESET}" if ok else f"{YELLOW}响应: {msg[:30]}{RESET}"
            print(f"  - {label:<16}: {status_tag}")
    else:
        print(f"\n[{BLUE}INFO{RESET}] Clash 代理端口 {mixed_port} 当前未在监听（内核未启动），配置已就绪，启动后即可直接生效。")

    # 9. 状态一致性检测报告
    print(f"\n{BOLD}{CYAN}======================== 环境一致性对照报告 ========================{RESET}")

    def report_row(item, sr_baseline, clash_state, is_match):
        badge = f"{GREEN}完全一致 (MATCH){RESET}" if is_match else f"{RED}不一致 (DIFF){RESET}"
        print(f"  * {item:<20}: 基准=[{sr_baseline}] -> 本机=[{clash_state}] {badge}")

    merge_has_sr = False
    if merge_file.exists():
        with open(merge_file, "r", encoding="utf-8") as f:
            mt = f.read()
        merge_has_sr = "sr-direct" in mt and "sr-proxy" in mt

    report_row("规则集订阅绑定", "已挂载 sr-direct/proxy", "已挂载" if merge_has_sr else "未配置", merge_has_sr)
    report_row("直连分流规则库", "84 条 (含小红书/抖音/快手)", f"{direct_count} 条", direct_ok and direct_count >= 80)
    report_row("AI 代理规则保护", "12 条 (强制走代理出口)", f"{proxy_count} 条", proxy_ok and proxy_count >= 10)
    report_row("虚拟 TUN 模式", "严格关闭 (False)", "已开启" if tun_mode else "关闭", not tun_mode)
    report_row("全局模式拦截", "禁用全局，使用 Rule", "全局(Global)" if current_mode == "global" else "规则(Rule)", current_mode != "global")
    report_row("自动同步周期", "24h 静默同步", "24h (86400s)", True)

    print(f"{BOLD}{CYAN}==================================================================={RESET}\n")

    # 10. 最终判定与提示
    is_fully_aligned = merge_has_sr and direct_ok and proxy_ok and not tun_mode and current_mode != "global"

    if is_fully_aligned:
        print(f"{BOLD}{GREEN}✔ 判定完成：本机 Clash Verge Rev 分流环境已与 Shadowrocket 完全一致！{RESET}")
        print(f"  - 小红书、抖音、快手等国内流量自动直连；")
        print(f"  - Claude / Anthropic 敏感流量自动强制代理；")
        print(f"  - 规则每天自动从 GitHub main 静默更新，双端同步维护。\n")
        print(f"{BOLD}生效操作指引：{RESET}")
        print(f"  打开 Clash Verge Rev，在配置列表中右键点击 {BOLD}{profile_name}{RESET} -> 选择 {BOLD}“刷新 (Refresh)”{RESET} 即可！\n")
    else:
        print(f"{BOLD}{YELLOW}⚠ 注意：检测到部分设置与基准环境不一致，建议：{RESET}")
        if current_mode == "global":
            print(f"  - 请在 Clash Verge 界面左侧或托盘将模式切换为 {BOLD}Rule（规则模式）{RESET}，不要使用 Global。")
        if tun_mode:
            print(f"  - 请关闭 Clash Verge 的 TUN 模式开关。")
        print()

if __name__ == "__main__":
    main()
